server:
  port: 8085

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.168.11.65:1521:orcl
    username: ECARD_V3_NEW
    password: ECARD_V3_NEW
    validation-query: SELECT 1 FROM DUAL
mybatis:
  mapper-locations: classpath:xml/*.xml
